### ISSUE TITLE
Viewer bundle URL

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/itk-viewer-material-ui#20]
@bnmajor I may have merged #19 to quickly -- shouldn't 

https://cdn.jsdelivr.net/npm/itk-vtk-viewer@11.12.1/dist/itkVtkViewer.min.js

be

https://cdn.jsdelivr.net/npm/itk-vtk-viewer@11.12.1/dist/itkVtkViewerCDN.js

?

**Comment by bnmajor** [comment]
Sorry, yes, fixed in #21
