### ISSUE TITLE
CSS style not being applied

### ISSUE THREAD

**Issue by labdala** [InsightSoftwareConsortium/itk-viewer-material-ui#28]
When running locally, I get this behavior. We are probably missing something when publishing it to jsdelivr.
![image](https://user-images.githubusercontent.com/60415505/183121400-93719f54-fdbe-45f0-8a5a-bc90197d2056.png)

**Comment by thewtex** [comment]
We will need to bundle the the contents of `dist/style.css` into `dist/materialUIMachineOption.js.es.js`. This will be a configuration option in either `vite.config.js` or `rollup.config.js`.
