### ISSUE TITLE
[itkwidgets / jupyterlite] Access to UI blocked by CORS policy

### ISSUE THREAD

**Issue by labdala** [InsightSoftwareConsortium/itk-viewer-material-ui#29]
I will add this here even though I do not have a lot of information about it. 
When I am running itkwidgets locally, I have no problems using this UI (other than the styling mentioned in #28). However, when trying to use the UI in JupyterLite (itkwidgets 1.0a6), I get an error:

```
Access to script at 'https://www.jsdelivr.com/package/npm/itk-viewer-material-ui@0/dist/materialUIMachineOptions.js.es.js' from origin 'https://kitware.github.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
![image](https://user-images.githubusercontent.com/60415505/183122416-4c26a9ea-a6d4-41c4-98ea-479850f429d4.png)

the behavior for bootstrap UI:
![image](https://user-images.githubusercontent.com/60415505/183122659-ef91eb49-174a-4f10-95df-4227e3dfd77a.png)

**Comment by thewtex** [comment]
Closing assuming this is the jsdelivr.com vs jsdeliver.net issue
