### ISSUE TITLE
Ride into the Sunset?

### ISSUE THREAD

**Issue by PaulHax** [InsightSoftwareConsortium/itk-viewer-material-ui#37]
I like the feel of Material, I like the tests, like the evenly spaced layout in this UI.  

The re-rendering of all components lag on each state change is bad.  With state changes on each camera movement after debouce, this issue is kind of critical.

**Comment by thewtex** [comment]
Let's take it to the Rodeo :horse_racing: :cow: :cactus: :cowboy_hat_face: per #39
